defaults

tls on
logfile ~/.local/state/msmtp/msmtp.log

account cultivate
host smtp.gmail.com
port 587
auth oauthbearer
from talati@getcultivate.ai
user talati@getcultivate.ai
passwordeval "python /usr/share/neomutt/oauth2/mutt_oauth2.py --encryption-pipe 'cat' --decryption-pipe 'cat' ~/.local/share/mail/oauth/cultivate"
