tap "FelixKratz/formulae"
tap "nikitabobko/tap"

cask "bitwarden"
cask "font-0xproto-nerd-font"
cask "ghostty"
cask "nikitabobko/tap/aerospace"

brew "FelixKratz/formulae/borders"
brew "lima"
brew "stow"
