IMAPAccount paypal
Host imap.gmail.com
User nicktalatipaypal@gmail.com
AuthMechs XOAuth2
PassCmd "python /usr/share/neomutt/oauth2/mutt_oauth2.py --encryption-pipe 'cat' --decryption-pipe 'cat' ~/.local/share/mail/oauth/paypal"
TLSType IMAPS

IMAPStore paypal-remote
Account paypal

MaildirStore paypal-local
Path ~/mail/nicktalatipaypal/
Inbox ~/mail/nicktalatipaypal/Inbox
Subfolders Verbatim

Channel paypal
Far :paypal-remote:
Near :paypal-local:
Patterns *
Create Both
SyncState *
Expunge Both
