[Unit]
StartLimitIntervalSec=300
StartLimitBurst=10

[Service]
ExecStart=
ExecStart=/usr/bin/goimapnotify -conf %h/.config/goimapnotify/%i.yaml
Environment="PATH=/usr/local/bin:/usr/bin:%h/.local/bin"
