IMAPAccount personal
Host imap.gmail.com
User nicktalati@gmail.com
AuthMechs XOAuth2
PassCmd "python /usr/share/neomutt/oauth2/mutt_oauth2.py --encryption-pipe 'cat' --decryption-pipe 'cat' ~/.local/share/mail/oauth/personal"
TLSType IMAPS

IMAPStore personal-remote
Account personal

MaildirStore personal-local
Path ~/mail/nicktalati/
Inbox ~/mail/nicktalati/Inbox
Subfolders Verbatim

Channel personal
Far :personal-remote:
Near :personal-local:
Patterns *
Create Both
SyncState *
Expunge Both
